CREATE TABLE EMP (
    EMPNO INT  PRIMARY KEY  ,
    ENAME VARCHAR(10) NOT NULL ,
    SALARY NUMERIC(6) DEFAULT 4000,
    COMM NUMERIC(6),
    JOB VARCHAR(10)
);


INSERT INTO EMP (EMPNO, ENAME, SALARY, COMM, JOB)
VALUES (101, 'SMITH', 5000, 500, 'CLERK');

INSERT INTO EMP (EMPNO, ENAME,  COMM, JOB)
VALUES (102, 'WARD', 500, 'SALES');

INSERT INTO EMP (EMPNO, ENAME, SALARY, JOB)
VALUES (103, 'WARD', 7500, 'SALES');

INSERT INTO EMP (EMPNO, ENAME, SALARY, JOB)
VALUES (104, 'FORD', 9500, 'ANALYST');


UPDATE EMP SET ENAME='JONES' WHERE EMPNO=103;
UPDATE EMP SET JOB='SALESMAN' WHERE EMPNO IN (102,103);

DELETE FROM EMP WHERE EMPNO=104;
DELETE FROM EMP WHERE ENAME='SMITH';






