CREATE TABLE EMP (
    EMPNO INT AUTO_INCREMENT PRIMARY KEY  ,
    ENAME VARCHAR(10) NOT NULL ,
    SALARY NUMERIC(6) DEFAULT 4000,
    COMM NUMERIC(6),
    JOB VARCHAR(10)
);


INSERT INTO EMP ( ENAME, SALARY, COMM, JOB)
VALUES ( 'SMITH', 5000, 500, 'CLERK');

INSERT INTO EMP (ENAME,  COMM, JOB)
VALUES ('WARD', 500, 'SALES');

INSERT INTO EMP (ENAME, SALARY, JOB)
VALUES ('WARD', 7500, 'SALES');

INSERT INTO EMP (ENAME, SALARY, JOB)
VALUES ('FORD', 9500, 'ANALYST');


UPDATE EMP SET ENAME='JONES' WHERE EMPNO=3;
UPDATE EMP SET JOB='SALESMAN' WHERE EMPNO IN (2,3);

DELETE FROM EMP WHERE EMPNO=4;
DELETE FROM EMP WHERE ENAME='SMITH';

SELECT * FROM EMP;

SELECT * FROM EMP WHERE COMM IS NULL;






